### ISSUE TITLE
Long Country Names Should Be Accompanied by Short Version

### ISSUE THREAD

**Issue by S73417H** [S73417H/MIDs#6]
The current list of MIDs are mapped against their "long" country name. This often contains redundant information such as sovereignty information (republic, democratic, kingdom, etc). An additional "short" country name should be added that does not include this information. This could be easily achieved in a script by looking up the country name from the ISO 3166 code once all MIDs have been mapped.

**Comment by ifreecarve** [comment]
Something like this (using [iso_country_codes](https://github.com/alexrabarts/iso_country_codes))?  

```ruby
require 'iso_country_codes'

JSON.parse(IO.read("mids.json")).each do |k, v| 
    code = IsoCountryCodes.find(v[1])
    puts "MID #{k}: #{code.numeric.to_i} - #{code.name}"  # see iso_country_codes synopsis
end
```

**Comment by S73417H** [comment]
Something like this would have been fine, however I think the original issue is a bit misguided to start with as most (if not all) of the country names are in their official and correct format. Only one or two stick out to me like "Qatar (State Of)". Technically I think this is correct in terms of ISO 3166 but many sources will simply specify "Qatar".
